apiVersion: v1
kind: Pod
metadata:
 name: my-sql

spec:
  containers:
  - image: mysql:latest
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom: 
        secretKeyRef:
          name: sqlsecret
          key: password
    - name: MYSQL_DATABASE
      valueFrom: 
        secretKeyRef:
          name: sqlsecret
          key: db     
    ports:
      - containerPort: 3306
        name: mysql