apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "500Mi"
          cpu: "1"
      volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d
        - name: html-volume
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 82
  volumes:
    - name: config-volume
      configMap:
        name: config-map
    - name: html-volume
      configMap:
        name: config-map-index
