apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: app1
  labels:
    app: app1
spec:
  containers:
  - name: app1
    image: mohameds2/app1:latest
    ports:
    - containerPort: 3000

---
apiVersion: v1
kind: Pod
metadata:
  name: app2
  labels:
    app: app2
spec:
  containers:
  - name: app2
    image: mohameds2/app2:latest
    ports:
    - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  type: NodePort              
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32001       

---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  type: NodePort              
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32002        

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
