apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: depi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod
  template:
    metadata:
      labels:
        app: pod
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80


