apiVersion: v1
kind: Service
metadata:
  name: multi-service
spec:
  type: ClusterIP
  selector:
      app: nginx
  ports:
    - name: port80
      port: 80
      targetPort: 80
    - name: port50
      port: 50
      targetPort: 50

