apiVersion: v1
kind: ConfigMap
metadata:
    name: config-map
data:
  
  default.conf: |
    server {
        listen 50;
        server_name localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html;
        }
    }
