apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 80

    - name: nginx2
      image: nginx
      volumeMounts:
        - name: config-volume2
          mountPath: /etc/nginx/conf.d
        - name: html-volume2
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 50
  volumes:
    - name: config-volume2
      configMap:
        name: config-map
    - name: html-volume2
      configMap:
        name: config-map-index2
    - name: html-volume
      configMap:
        name: config-map-index
